config/routes.rb
Rails.application.routes.draw do
  root "tweeets#index"
  devise_for :users
  resources :tweeets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
belongs_to :user, :optional => true
validates_length_of :tweeet, :within =>1...140
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      has_many :tweeets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy,]

  def index
    @tweeets = Tweeet.all.order("created_at DESC")
  end

  def show
  end

  def new
    if params[:back]
      @tweeet = Tweeet.new(tweeet_params)
    else
      @tweeet = Tweeet.new
    end
  end

  def edit
  end

  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to root_path, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
      @tweeet = Tweeet.new(tweeet_params)
      render :new if @tweeet.invalid?
    end
    def back
      @tweeet = Tweeet.edit(tweeet_params)
      render :choose_new_or_edit if @tweeet.invalid?
    end
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to root_path, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_tweeet
    @tweeet = Tweeet.find(params[:id])
  end

  def tweeet_params
    params.require(:tweeet).permit(:tweeet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
  def choose_new_or_edit
         if action_name == 'new' || action_name == 'confirm'
             confirm_tweeets_path
         elsif action_name == 'edit'
             tweeet_path
         end
     end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Clone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if flash[:notice] %>
  		<div class="notification is-primary global-notification">
  			<p class="notice"><%= notice %></p>
  		</div>
  	<% end %>
  	<% if flash[:alert] %>
  		<div class="notification is-danger global-notification">
  			<p class="alert"><%= alert %></p>
  		</div>
  	<% end %>

  	<nav class="navbar is-info">
  		<div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-7">Twitter Clone</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
  		</div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
          <div class="navbar-item">
					 <div class="field is-grouped">

             <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
             <% else %>
             <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
             </p>
					 	 <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
             </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>

    <%= yield %>
<br>
<br>
<br>
<br>




</body>
</html>
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Twitter Clone</strong> by <a href="https://github.com/Fozi96/Twittery.git">Fozia Fayib</a>. Hola, let's die together.
       <a href="https://diver.diveintocode.jp">let's dive together </a>.
    </p>
  </div>
</footer>

app/views/tweeets/_feed.html.erb
<div class="column is-half">

  <% if user_signed_in? %>

	<article class="media box">
		<figure class="media-left">
			<p class="image is-64x64">
				<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
			</p>
		</figure>


		<div class="media-content">

      <%= link_to 'New Tweet', new_tweeet_path %>
           <% @tweeets.each do |tweeet| %>
            <hr>
              <div>
                <%= tweeet.tweeet %>
              </div>

              <div>
                <%= link_to 'Post', tweeet %>
                <%= link_to 'Edit', edit_tweeet_path(tweeet) %>
                <%= link_to 'Destroy', tweeet, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>

           <% end %>
      <br>


		</div>
	</article>
  <% end %>


<% @tweeets.each do | tweeet | %>

  <div class="box">
  	<article class="media">
  		<div class="media-left">

  		</div>

  		<div class="media-content">
  			<div class="content">

  				<p><%= tweeet.tweeet %></p>

  			</div>

        <% if user_signed_in? && current_user.id == tweeet.user_id %>
        
  			<nav class="level">
  				<div class="level-left is-mobile">
  					<%= link_to tweeet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweeet_path(tweeet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweeet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
        <% end %>
  		</div>
  	</article>
  </div>
<% end %>
</div>

app/views/tweeets/_form.html.erb
<%= form_with(model: @tweeet, local: true, url: choose_new_or_edit) do |form| %>
  <% if @tweeet.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(tweeet.errors.count, "error") %> prevented this tweet from being saved :</h2>

  <ul>
    <% tweeet.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
  <% end %>

  <div class="field">
  
    <%= form.text_area :tweeet %>
  </div>

  <div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/tweeets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweeets</p>
						<p class="title is-6"><%= current_user.tweeets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">12</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">5</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweeets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			#BlackPanther
		</a>
		<a class="panel-block">
			#Stopkillinganimals
		</a>
		<a class="panel-block">
			#Al-jerrahnews
		</a>
		<a class="panel-block">
			#Covid-19
		</a>

	</nav>
</div>

app/views/tweeets/_who-to-follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>

	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Jules</strong>
						<small>Jules</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Cedrick Justin</strong>
						<small>Cedrick Justin</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Robert </strong>
						<small>Robert</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/tweeets/confirm.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		 <div class="column is-4">

		<h2 class="title is-2">Confirmation Page</h2>


<%= form_with(model: @tweeet, url: tweeets_path, local:true) do |form| %>
    <%= form.hidden_field :tweeet %>
    <p class="title is-5"> Your Tweet: <%= @tweeet.tweeet %></p>
  <%= form.submit  "Submit" %>
<% end %>
<%= form_with(model: @tweeet, url: new_tweeet_path, local:true,method: 'get') do |form| %>
    <%= form.hidden_field :tweeet %>
  <%= form.submit  "back", name: 'back' %>
<% end %>



     </div>

    </div>
   </div>
  </div>

app/views/tweeets/edit.html.erb
<h1>Edit your Tweet</h1>

<%= render 'form', tweeet: @tweeet %>
<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">

      <% if user_signed_in? %>
      <%= render 'profile' %>
      <% else %>
      <%= render 'trends' %>
      <% end %>

       <%= render 'feed' %>
       <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/tweeets/new.html.erb
<div class="section">
	<div class="container">
	<div class="columns is-centered">

		<div class="column is-4">

		<h2 class="title is-2">New Tweet</h2>

	  <div class="field">
	  	<div class="control">
	    <%= render 'form', tweeet: @tweeet %>
	  	</div>
		</div>



<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>